### ISSUE TITLE
Make it more customizeable

### ISSUE THREAD

**Issue by CamiloMM** [mattohagan/jot#2]
Hi, the idea for this extension is awesome, but I'd love if it was just a bit customizeable.

For example, I find that thick border extremely jarring, and would prefer full bleed images. And for the images, I'd love if I could choose them, maybe even making it an URL list or something. This could be sync-able (even if it doesn't work offline).

Point being; URL lists for images and remove-that-border option would be awesome to have. Right now it doesn't seem to have any sort of configuration so it could be a bit of work though.

**Comment by whosnorman** [comment]
The next update definitely has customization in store, that's been the most popular request. I've been thinking of some fun things to do with the images that will probably have to wait til the second update, I'll add url driven to the list!

**Comment by CamiloMM** [comment]
@mattohagan That's awesome then! Thanks, this extension is really great. Not having to see the "recent websites" saves me from being tempted by time wastes and click-craving :)
