### ISSUE TITLE
backspace to end delete the rest of the list?

### ISSUE THREAD

**Issue by jpmorris** [mattohagan/jot#3]
Is this the desired behavior.  I was expecting that you just backspace  on the 3rd item (out of 10 that the 3rd item would be gone.  How do we remove items?  Currently, I delete an item and the rest of the list disappears.  If this is the desired behavior it seems like a horrible idea.

**Comment by whosnorman** [comment]
definitely not desired behavior, I've been trying to recreate it but haven't had any success. I'll keep looking into it
